catcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.index, name='index'),
  path('about/', views.about, name='about'),
  
  path('cats/', views.cats_index, name='cats'),
  path('cats/<int:cat_id>', views.cat_show, name='show'),
  path('cats/create/', views.CatCreate.as_view(), name='cats_create'),
  path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cats_update'),
  path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cats_delete'),

  path('user/<username>', views.profile, name='profile'),

  path('cattoys/', views.cattoys_index, name='cattoys_index'),
  path('cattoys/<int:cattoy_id>', views.cattoys_show, name='cattoys_show'),
  path('cattoys/create/', views.CatToyCreate.as_view(), name='cattoys_create'),
  path('cattoys/<int:pk>/update/', views.CatToyUpdate.as_view(), name='cattoys_update'),
  path('cattoys/<int:pk>/delete/', views.CatToyDelete.as_view(), name='cattoys_delete'),

  path('login/', views.login_view, name='login'),
  path('logout/', views.logout_view, name='logout'),
  path('signup/', views.signup_view, name='signup'),

]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class CatToy(models.Model):
  name = models.CharField(max_length=100)
  color = models.CharField(max_length=50)

  def __str__(self):
    return self.name

class Cat(models.Model):
  name = models.CharField(max_length=100)
  breed = models.CharField(max_length=100)
  description = models.CharField(max_length=250)
  age = models.IntegerField()
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  cattoys = models.ManyToManyField(CatToy)
  def __str__(self):
    return f'{self.name} - {self.description}'

main_app/views.py
from django.contrib import auth
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView, DeleteView


# Create your views here.
from .models import Cat, CatToy


def about(request):
  return render(request, 'about.html')


def index(request):
  return render(request, 'index.html')

@login_required
def profile(request, username):
  user = User.objects.get(username=username)
  cats = Cat.objects.filter(user=user)
  return render(request, 'profile.html', {'username': username, 'cats': cats})


def cats_index(request):
  cats = Cat.objects.all()
  data = {'cats': cats}
  return render(request, 'cats/index.html', data)


def cat_show(request, cat_id):
  cat = Cat.objects.get(id=cat_id)
  return render(request, 'cats/show.html', {'cat': cat})


class CatCreate(CreateView):
  model = Cat
  fields = ['name', 'breed', 'description', 'age', 'cattoys']
  success_url = '/cats'

  def form_valid(self, form) -> HttpResponse:
    self.object = form.save(commit=False)
    self.object.user = self.request.user
    self.object.save()
    return HttpResponseRedirect('/cats')


class CatUpdate(UpdateView):
  model = Cat
  fields = ['name', 'breed', 'description', 'age', 'cattoys']

  def form_valid(self, form):
    self.object = form.save(commit=False)
    self.object.save()
    return HttpResponseRedirect(f'/cats/{self.object.pk}')


@method_decorator(login_required, name='dispatch')
class CatDelete(DeleteView):
  model = Cat
  fields = '/cats'
  success_url = '/cats'


def cattoys_index(request):
  cattoys = CatToy.objects.all()
  return render(request, 'cattoys/index.html', {'cattoys': cattoys})


def cattoys_show(request, cattoy_id):
  cattoy = CatToy.objects.get(id=cattoy_id)
  return render(request, 'cattoys/show.html', {'cattoy': cattoy})


class CatToyCreate(CreateView):
  model = CatToy
  fields = '__all__'
  success_url = '/cattoys'

  def form_valid(self, form) -> HttpResponse:
    self.object = form.save(commit=False)
    self.object.user = self.request.user
    self.object.save()
    return HttpResponseRedirect('/cattoys')
  pass


class CatToyUpdate(UpdateView):
  model = CatToy
  fields = ['name', 'color']
  success_url = '/cattoys'
  pass


class CatToyDelete(DeleteView):
  model = CatToy
  success_url = '/cattoys'
  pass


def login_view(request):
  if request.method == 'POST':
    form = AuthenticationForm(request, request.POST)

    if not form.is_valid():
      print('-----------------------The username and/or password was incorrect')
      return HttpResponseRedirect('/login')

    u = form.cleaned_data['username']
    p = form.cleaned_data['password']
    user = authenticate(username=u, password=p)

    if not user.is_active:
      print('The account has been disabled')
      return HttpResponseRedirect('/login')

    login(request, user)
    return HttpResponseRedirect(f'/user/{u}')

  else:
    form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def logout_view(request):
  logout(request)
  return HttpResponseRedirect('/cats')


def signup_view(request):
  if request.method is not 'POST':
    form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})
  form = UserCreationForm(request.POST)
  if form.is_valid():
    user = form.save()
    login(request, user)
    return HttpResponseRedirect('/cats')

main_app/templates/about.html
<!DOCTYPE html>
<html>
  <head>
    <title>About the catcollector...</title>
  </head>
  <body>
    <h1>About the catcollector...</h1>
    <hr />
    <p>Hire the catcollector!</p>
    <footer>a footer goes here, this could probably be templated</footer>
  </body>
</html>

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>CatCollector</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.css">
  </head>
  <body>
      <header>
      {% if user.is_authenticated %}
        <span><a href="{% url 'profile' user.username %}">Hello, {{ user.username }}!</a></span>
        <span> | </span>
        <span><a href="{% url 'logout' %}">Logout</a></span>
        <span> | </span>
      {% else %}
        <span><a href="{% url 'login' %}">Login</a></span>
        <span> | </span>
        <span><a href="{% url 'signup' %}">SignUp</a></span>
      {% endif %}
      </header>
      <hr />
      <a href="/cats">
          <h1>catcollector</h1>
      </a>
      <hr />
      {% block content %}
      {% endblock %}
      <footer>
        All Rights Reserved, catcollector 2018
      </footer>
  </body>
</html>

main_app/templates/cats/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <a href="/cats/create">Add a New Cat!</a>
  <hr />
  {% for cat in cats %}
    <a href='/cats/{{cat.id}}'>
      <p>Name: {{ cat.name }}</p>
    </a>
    <a href='/user/{{cat.user.username}}'>
      <p>Adopted By: {{cat.user.username}}</p>
    </a>
    {% if cat.age > 0 %}
      <p>Age: {{ cat.age }}</p>
    {% else %}
      <p>Age: Kitten</p>
    {% endif %}
    {% for cattoy in cat.cattoys.all %}
      <div>{{cattoy.name}}</div>
      {% empty %}
      <div>Cat Has No Toys :(</div>
    {% endfor %}
    <div>
      <a href="{% url 'cats_update' cat.id %}">Edit</a>
      <a href="{% url 'cats_delete' cat.id %}">Delete</a>
    </div>
    <hr />
  {% endfor %}
{% endblock %}

main_app/templates/cats/show.html
<h2>{{cat.name}}</h2>
<ul>
  <li>
    age: {{cat.age}}
  </li>
  <li>
    breed: {{cat.breed}}
  </li>
  <li>
    description: {{cat.description}}
  </li>
</ul>

main_app/templates/cattoys/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Cat Toy List</h1>

{% for cattoy in cattoys %}
    <div>
        <a href="{% url 'cattoys_show' cattoy.id %}">
            <div class="card-content">
                <span>{{ cattoy.name }}</span>
                <p>Color: {{ cattoy.color }}</p>
            </div>
        </a>
    </div>
{% endfor %}

{% endblock %}

main_app/templates/cattoys/show.html
{% extends 'base.html' %}
{% block content %}

<h1>Cat Toy Details</h1>

<div>
  <div>
    <span>{{ cattoy.name }}</span>
    <p>Color: {{ cattoy.color }}</p>
  </div>
    <div>
      <span>{{ cattoy.name }}</span>
      <p>Color: {{ cattoy.color }}</p>
      <p>Owned by:</p>
      {% for cat in cattoy.cat_set.all %}
        <p>{{cat.name}}</p>
      {% empty %}
        <p>Nobody Has This Toy</p>
      {% endfor %}
    </div>
  <div>
    <a href="{% url 'cattoys_update' cattoy.id %}">Edit</a>
    <a href="{% url 'cattoys_delete' cattoy.id %}">Delete</a>
  </div>
</div>
{% endblock %}

main_app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>catcollector</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>
  <body>
    <h1>/ᐠ｡‸｡ᐟ\</h1>
    <h1>/ᐠ｡‸｡ᐟ\</h1>
    <h1>/ᐠ｡‸｡ᐟ\</h1>
    <h1>/ᐠ｡‸｡ᐟ\</h1>
    <h1>/ᐠ｡‸｡ᐟ\</h1>
    <h1>/ᐠ｡‸｡ᐟ\</h1>
    <h1>/ᐠ｡‸｡ᐟ\</h1>
    <h1>/ᐠ｡‸｡ᐟ\</h1>
    <hr />
    <a href="/cats">View All My Cats!</a>
        <header>
      {% if user.is_authenticated %}
      <span><a href="{% url 'profile' user.username %}">Hello, {{ user.username }}!</a></span>
      <span> | </span>
      <span><a href="{% url 'logout' %}">Logout</a></span>
      <span> | </span>
      {% else %}
      <span><a href="{% url 'login' %}">Login</a></span>
      <span> | </span>
      <span><a href="{% url 'signup' %}">SignUp</a></span>
      {% endif %}
      <a href="/cats">
          <h1>catcollector</h1>
      </a>
    </header>
    <hr />
    <footer>a footer goes here, this could probably be templated</footer>
  </body>
</html>

main_app/templates/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Login</h1>
<form method="POST" action=".">
  {% csrf_token %}
  {{ form.as_p}}
  <input type="submit" value="Submit" />
</form>

{% endblock %}

main_app/templates/main_app/cat_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete Cat</h1>

<p>Are you sure you want to delete this cat: {{ cat }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

main_app/templates/main_app/cat_form.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
  {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!">
</form>
{% endblock content %}

main_app/templates/main_app/cattoy_confirm_delete.html
<!-- main_app/templates/main_app/cattoy_confirm_delete.html -->
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Cat Toy</h1>

    <h4>Are you sure you want to delete <strong>{{ cattoy }}</strong>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!">
        <a href="{% url 'cattoys_show' cattoy.id %}">Cancel</a>
    </form>
{% endblock %}

main_app/templates/main_app/cattoy_form.html
<!-- main_app/templates/main_app/cattoy_form.html -->
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!">
    </form>
{% endblock %}

main_app/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>{{ username }}'s collection:</h1>

{% for cat in cats %}
<a href="/cats/{{ cat.id }}">
  <h3>{{ cat.name }}</h3>
</a>

{% endfor %}

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}